#!/bin/bash

git clone git@github.com:Credify/account-srvc
git clone git@github.com:Credify/api-funnel-orchestrator
git clone git@github.com:Credify/architecture-decision-records
git clone git@github.com:Credify/avro-creditline-lib
git clone git@github.com:Credify/avro-extensions
git clone git@github.com:Credify/avro-funnel-lib
git clone git@github.com:Credify/avro-schemas
git clone git@github.com:Credify/borrower-funnel-orch
git clone git@github.com:Credify/borrower-portal-orch
git clone git@github.com:Credify/brokerage-events
git clone git@github.com:Credify/brokerage-srvc
git clone git@github.com:Credify/card-client
git clone git@github.com:Credify/card-dispute-srvc
git clone git@github.com:Credify/card-funding-monitoring-srvc
git clone git@github.com:Credify/card-funding-srvc
git clone git@github.com:Credify/card-srvc
git clone git@github.com:Credify/claude_memory
git clone git@github.com:Credify/core-arix-srvc
git clone git@github.com:Credify/crb-cos-client
git clone git@github.com:Credify/credify-checkstyle
git clone git@github.com:Credify/credit-decision-client
git clone git@github.com:Credify/credit-decision-srvc
git clone git@github.com:Credify/credit-monitoring-srvc
git clone git@github.com:Credify/creditline-authorization-decision-srvc
git clone git@github.com:Credify/creditline-disbursement-srvc
git clone git@github.com:Credify/creditline-fee-srvc
git clone git@github.com:Credify/creditline-partner-srvc
git clone git@github.com:Credify/creditline-payment-events
git clone git@github.com:Credify/creditline-payment-srvc
git clone git@github.com:Credify/creditline-review-client
git clone git@github.com:Credify/creditline-review-srvc
git clone git@github.com:Credify/creditline-servicing-client
git clone git@github.com:Credify/creditline-servicing-srvc
git clone git@github.com:Credify/creditline-statement-srvc
git clone git@github.com:Credify/cross-sell-srvc
git clone git@github.com:Credify/customer-performance-client
git clone git@github.com:Credify/customer-performance-srvc
git clone git@github.com:Credify/disbursement-srvc
git clone git@github.com:Credify/doc-mgt-client
git clone git@github.com:Credify/doc-mgt-srvc
git clone git@github.com:Credify/doc-mgt-templates
git clone git@github.com:Credify/dosh-rewards-events
git clone git@github.com:Credify/dosh-rewards-srvc
git clone git@github.com:Credify/email-mgt-srvc
git clone git@github.com:Credify/event-dispatcher-framework
git clone git@github.com:Credify/ext-webhook-gateway-srvc
git clone git@github.com:Credify/external-actor-engagement-srvc
git clone git@github.com:Credify/external-bank-account-srvc
git clone git@github.com:Credify/funnel-ui
git clone git@github.com:Credify/github-terraform
git clone git@github.com:Credify/k8s-template
git clone git@github.com:Credify/lead-srvc
git clone git@github.com:Credify/ledger-client
git clone git@github.com:Credify/ledger-srvc
git clone git@github.com:Credify/llm-context
git clone git@github.com:Credify/loan-app-client
git clone git@github.com:Credify/loan-app-creation-client
git clone git@github.com:Credify/loan-app-creation-srvc
git clone git@github.com:Credify/loan-review-client
git clone git@github.com:Credify/loan-review-srvc
git clone git@github.com:Credify/loan-utils
git clone git@github.com:Credify/login-srvc
git clone git@github.com:Credify/next-best-action-srvc
git clone git@github.com:Credify/offline-report-srvc
git clone git@github.com:Credify/ondemand
git clone git@github.com:Credify/openrewrite-recipes
git clone git@github.com:Credify/optimizely-integration
git clone git@github.com:Credify/path-to-approval-srvc
git clone git@github.com:Credify/pcl-ai-tools
git clone git@github.com:Credify/pcl-application-srvc
git clone git@github.com:Credify/pcl-decision-engine-client
git clone git@github.com:Credify/pcl-draw-fraud-detection
git clone git@github.com:Credify/pcl-draw-srvc
git clone git@github.com:Credify/pcl-program-definition-eligibility-srvc
git clone git@github.com:Credify/pcl-program-definition-mgmt-srvc
git clone git@github.com:Credify/pcl-query-transactions-srvc
git clone git@github.com:Credify/pcl-rewards-redeem-srvc
git clone git@github.com:Credify/pl-application-srvc
git clone git@github.com:Credify/program-definition-srvc
git clone git@github.com:Credify/promotion-srvc
git clone git@github.com:Credify/qa-automation
git clone git@github.com:Credify/qa-jenkins-jobs
git clone git@github.com:Credify/rewards-analytics-srvc
git clone git@github.com:Credify/rewards-client
git clone git@github.com:Credify/rewards-srvc
git clone git@github.com:Credify/shared-lib
git clone git@github.com:Credify/spectrum-api-client
git clone git@github.com:Credify/spectrum-docker
git clone git@github.com:Credify/spectrum-event-listener-srvc
git clone git@github.com:Credify/spectrum-extension-client
git clone git@github.com:Credify/spectrum-extension-srvc
git clone git@github.com:Credify/spectrum-read-srvc
git clone git@github.com:Credify/springboot-template
git clone git@github.com:Credify/sumo
git clone git@github.com:Credify/sumologic-config
git clone git@github.com:Credify/task-queue-framework-lib
git clone git@github.com:Credify/upflow2-pcl-dags
